export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { defineAlertElements } from "./define";
export { defineAlertElements as defineElements } from "./define";
export { createAlertElement, createElement, getPartSpec } from "./shared";
export type { AlertHostElement } from "./shared";
export { AlertWebElement, createAlertWebComponent } from "./alert-element";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
export { Action } from "./parts/Action";
export type { ActionElement } from "./parts/Action";
export { Cancel } from "./parts/Cancel";
export type { CancelElement } from "./parts/Cancel";
export { Close } from "./parts/Close";
export type { CloseElement } from "./parts/Close";
export { Description } from "./parts/Description";
export type { DescriptionElement } from "./parts/Description";
export { Title } from "./parts/Title";
export type { TitleElement } from "./parts/Title";
