export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { defineAvatarElements } from "./define";
export { defineAvatarElements as defineElements } from "./define";
export { createAvatarElement, createElement, getPartSpec } from "./shared";
export type { AvatarHostElement } from "./shared";
export { AvatarElement, AvatarElement as AvatarWebElement } from "./avatar-element";
export type { AvatarImageLoadingStatus } from "./avatar-element";
export { createAvatarWebComponent } from "./avatar-web-component";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
export { Fallback } from "./parts/Fallback";
export type { FallbackElement } from "./parts/Fallback";
export { Group } from "./parts/Group";
export type { GroupElement } from "./parts/Group";
export { Image } from "./parts/Image";
export type { ImageElement } from "./parts/Image";
