export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { defineAccordionElements } from "./define";
export { defineAccordionElements as defineElements } from "./define";
export { createAccordionElement, createElement, getPartSpec } from "./shared";
export type { AccordionHostElement } from "./shared";
export { AccordionElement } from "./accordion-element";
export { createAccordionWebComponent } from "./accordion-web-component";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
export { Button } from "./parts/Button";
export type { ButtonElement } from "./parts/Button";
export { Content } from "./parts/Content";
export type { ContentElement } from "./parts/Content";
export { Header } from "./parts/Header";
export type { HeaderElement } from "./parts/Header";
export { Item } from "./parts/Item";
export type { ItemElement } from "./parts/Item";
export { Panel } from "./parts/Panel";
export type { PanelElement } from "./parts/Panel";
export { Trigger } from "./parts/Trigger";
export type { TriggerElement } from "./parts/Trigger";
