export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { defineToggleGroupElements } from "./define";
export { defineToggleGroupElements as defineElements } from "./define";
export { createToggleGroupElement, createElement, getPartSpec } from "./shared";
export type { ToggleGroupHostElement } from "./shared";
export { ToggleGroupWebElement, createToggleGroupWebComponent } from "./toggle-group-element";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
export { Item } from "./parts/Item";
export type { ItemElement } from "./parts/Item";
