export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { defineCardElements } from "./define";
export { defineCardElements as defineElements } from "./define";
export { createCardElement, createElement, getPartSpec } from "./shared";
export type { CardHostElement } from "./shared";
export { CardWebElement, createCardWebComponent } from "./card-element";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
export { Content } from "./parts/Content";
export type { ContentElement } from "./parts/Content";
export { Description } from "./parts/Description";
export type { DescriptionElement } from "./parts/Description";
export { Footer } from "./parts/Footer";
export type { FooterElement } from "./parts/Footer";
export { Header } from "./parts/Header";
export type { HeaderElement } from "./parts/Header";
export { Title } from "./parts/Title";
export type { TitleElement } from "./parts/Title";
