export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { defineInputElements } from "./define";
export { defineInputElements as defineElements } from "./define";
export { createInputElement, createElement, getPartSpec } from "./shared";
export type { InputHostElement } from "./shared";
export { InputElement, InputElement as InputWebElement } from "./input-element";
export { createInputWebComponent } from "./input-web-component";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
