export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { defineAspectRatioElements } from "./define";
export { defineAspectRatioElements as defineElements } from "./define";
export { createAspectRatioElement, createElement, getPartSpec } from "./shared";
export type { AspectRatioHostElement } from "./shared";
export { AspectRatioElement, AspectRatioElement as AspectRatioWebElement, resolveAspectRatio } from "./aspect-ratio-element";
export { createAspectRatioWebComponent } from "./aspect-ratio-web-component";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
