export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { defineArrowElements } from "./define";
export { defineArrowElements as defineElements } from "./define";
export { createArrowElement, createElement, getPartSpec } from "./shared";
export type { ArrowHostElement } from "./shared";
export { ArrowElement, ArrowElement as ArrowWebElement } from "./arrow-element";
export { createArrowWebComponent } from "./arrow-web-component";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
