export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { defineSplitterElements } from "./define";
export { defineSplitterElements as defineElements } from "./define";
export { createSplitterElement, createElement, getPartSpec } from "./shared";
export type { SplitterHostElement } from "./shared";
export { SplitterWebElement, createSplitterWebComponent } from "./splitter-element";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
export { Panel } from "./parts/Panel";
export type { PanelElement } from "./parts/Panel";
export { Separator } from "./parts/Separator";
export type { SeparatorElement } from "./parts/Separator";
