export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { defineTooltipElements } from "./define";
export { defineTooltipElements as defineElements } from "./define";
export { createTooltipElement, createElement, getPartSpec } from "./shared";
export type { TooltipHostElement } from "./shared";
export { TooltipWebElement, createTooltipWebComponent } from "./tooltip-element";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
export { Content } from "./parts/Content";
export type { ContentElement } from "./parts/Content";
export { Trigger } from "./parts/Trigger";
export type { TriggerElement } from "./parts/Trigger";
