import DefaultTheme from "vitepress/theme";
import "./style.css";
import { installCalendarExamples } from "./calendar-examples";
import { installComboboxExamples } from "./combobox-examples";
import { installCommandExamples } from "./command-examples";
import { installContextMenuExamples } from "./context-menu-examples";
import { installDatepickerExamples } from "./datepicker-examples";
import { installDisclosureExamples } from "./disclosure-examples";
import { installDrawerExamples } from "./drawer-examples";
import { installDropdownMenuExamples } from "./dropdown-menu-examples";
import { installHoverCardExamples } from "./hover-card-examples";
import { installGridExamples } from "./grid-examples";
import { installMenubarExamples } from "./menubar-examples";
import { installNavigationMenuExamples } from "./navigation-menu-examples";
import { installPaginationExamples } from "./pagination-examples";
import { installPortalExamples } from "./portal-examples";
import { installPopoverExamples } from "./popover-examples";
import { installProgressExamples } from "./progress-examples";
import { installRadioExamples } from "./radio-examples";
import { installScrollAreaExamples } from "./scroll-area-examples";
import { installSidebarExamples } from "./sidebar-examples";
import { installSpinnerExamples } from "./spinner-examples";
import { installSelectExamples } from "./select-examples";
import { installSwitchExamples } from "./switch-examples";
import { installTableExamples } from "./table-examples";
import { installTabsExamples } from "./tabs-examples";
import { installTextareaExamples } from "./textarea-examples";
import { installToastExamples } from "./toast-examples";
import { installTooltipExamples } from "./tooltip-examples";
import { installTreegridExamples } from "./treegrid-examples";
import { defineAccordionElements } from "@ariaui-web/accordion";
import { defineAlertElements } from "@ariaui-web/alert";
import { defineAlertDialogElements } from "@ariaui-web/alert-dialog";
import { defineArrowElements } from "@ariaui-web/arrow";
import { defineAspectRatioElements } from "@ariaui-web/aspect-ratio";
import { defineAvatarElements } from "@ariaui-web/avatar";
import { defineBadgeElements } from "@ariaui-web/badge";
import { defineBreadcrumbElements } from "@ariaui-web/breadcrumb";
import { defineButtonElements } from "@ariaui-web/button";
import { defineCalendarElements } from "@ariaui-web/calendar";
import { defineCardElements } from "@ariaui-web/card";
import { defineCarouselElements } from "@ariaui-web/carousel";
import { defineCheckboxElements } from "@ariaui-web/checkbox";
import { defineComboboxElements } from "@ariaui-web/combobox";
import { defineCommandElements } from "@ariaui-web/command";
import { defineContextMenuElements } from "@ariaui-web/context-menu";
import { defineDatepickerElements } from "@ariaui-web/datepicker";
import { defineDialogElements } from "@ariaui-web/dialog";
import { defineDisclosureElements } from "@ariaui-web/disclosure";
import { defineDrawerElements } from "@ariaui-web/drawer";
import { defineDropdownMenuElements } from "@ariaui-web/dropdown-menu";
import { defineFocusScopeElements } from "@ariaui-web/focus-scope";
import { defineGridElements } from "@ariaui-web/grid";
import { defineHoverCardElements } from "@ariaui-web/hover-card";
import { defineInputElements } from "@ariaui-web/input";
import { defineInputOtpElements } from "@ariaui-web/input-otp";
import { defineKbdElements } from "@ariaui-web/kbd";
import { defineLabelElements } from "@ariaui-web/label";
import { defineListboxElements } from "@ariaui-web/listbox";
import { defineMenubarElements } from "@ariaui-web/menubar";
import { defineNavigationMenuElements } from "@ariaui-web/navigation-menu";
import { definePaginationElements } from "@ariaui-web/pagination";
import { definePopoverElements } from "@ariaui-web/popover";
import { definePortalElements } from "@ariaui-web/portal";
import { defineProgressElements } from "@ariaui-web/progress";
import { defineRadioElements } from "@ariaui-web/radio";
import { defineScrollAreaElements } from "@ariaui-web/scroll-area";
import { defineSelectElements } from "@ariaui-web/select";
import { defineSeparatorElements } from "@ariaui-web/separator";
import { defineSidebarElements } from "@ariaui-web/sidebar";
import { defineSkeletonElements } from "@ariaui-web/skeleton";
import { defineSliderElements } from "@ariaui-web/slider";
import { defineSlotElements } from "@ariaui-web/slot";
import { defineSpinbuttonElements } from "@ariaui-web/spinbutton";
import { defineSpinnerElements } from "@ariaui-web/spinner";
import { defineSplitterElements } from "@ariaui-web/splitter";
import { defineSwitchElements } from "@ariaui-web/switch";
import { defineTableElements } from "@ariaui-web/table";
import { defineTabsElements } from "@ariaui-web/tabs";
import { defineTextareaElements } from "@ariaui-web/textarea";
import { defineToastElements } from "@ariaui-web/toast";
import { defineToggleElements } from "@ariaui-web/toggle";
import { defineToggleGroupElements } from "@ariaui-web/toggle-group";
import { defineTooltipElements } from "@ariaui-web/tooltip";
import { defineTreegridElements } from "@ariaui-web/treegrid";
import { defineTreeviewElements } from "@ariaui-web/treeview";
import { defineUploadElements } from "@ariaui-web/upload";

function installSliderExamples() {
  document.addEventListener("valuechange", (event) => {
    const root = event.target;
    if (!(root instanceof HTMLElement) || !root.matches("aria-slider[data-slider-controlled]")) return;
    const value = (event as CustomEvent<{ value?: number | number[] }>).detail?.value;
    if (value !== undefined) root.setAttribute("value", Array.isArray(value) ? value.join(",") : String(value));
  });
}

export default {
  extends: DefaultTheme,
  enhanceApp() {
    if (typeof window !== "undefined") {
      defineAccordionElements();
      defineAlertElements();
      defineAlertDialogElements();
      defineArrowElements();
      defineAspectRatioElements();
      defineAvatarElements();
      defineBadgeElements();
      defineBreadcrumbElements();
      defineButtonElements();
      defineCalendarElements();
      defineCardElements();
      defineCarouselElements();
      defineCheckboxElements();
      defineComboboxElements();
      defineCommandElements();
      defineContextMenuElements();
      defineDatepickerElements();
      defineDialogElements();
      defineDisclosureElements();
      defineDrawerElements();
      defineDropdownMenuElements();
      defineFocusScopeElements();
      defineGridElements();
      defineHoverCardElements();
      defineInputElements();
      defineInputOtpElements();
      defineKbdElements();
      defineLabelElements();
      defineListboxElements();
      defineMenubarElements();
      defineNavigationMenuElements();
      definePaginationElements();
      definePopoverElements();
      definePortalElements();
      defineProgressElements();
      defineRadioElements();
      defineScrollAreaElements();
      defineSelectElements();
      defineSeparatorElements();
      defineSidebarElements();
      defineSkeletonElements();
      defineSliderElements();
      defineSlotElements();
      defineSpinbuttonElements();
      defineSpinnerElements();
      defineSplitterElements();
      defineSwitchElements();
      defineTableElements();
      defineTabsElements();
      defineTextareaElements();
      defineToastElements();
      defineToggleElements();
      defineToggleGroupElements();
      defineTooltipElements();
      defineTreegridElements();
      defineTreeviewElements();
      defineUploadElements();
      installCalendarExamples();
      installComboboxExamples();
      installCommandExamples();
      installContextMenuExamples();
      installDatepickerExamples();
      installDisclosureExamples();
      installDrawerExamples();
      installDropdownMenuExamples();
      installHoverCardExamples();
      installGridExamples();
      installMenubarExamples();
      installNavigationMenuExamples();
      installPaginationExamples();
      installPortalExamples();
      installPopoverExamples();
      installProgressExamples();
      installRadioExamples();
      installScrollAreaExamples();
      installSidebarExamples();
      installSelectExamples();
      installSliderExamples();
      installSpinnerExamples();
      installSwitchExamples();
      installTableExamples();
      installTabsExamples();
      installTextareaExamples();
      installToastExamples();
      installTooltipExamples();
      installTreegridExamples();
    }
  },
};
