export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { defineInputOtpElements } from "./define";
export { defineInputOtpElements as defineElements } from "./define";
export { createInputOtpElement, createElement, getPartSpec } from "./shared";
export type { InputOtpHostElement } from "./shared";
export { InputOtpElement, InputOtpElement as InputOtpWebElement } from "./input-otp-element";
export { createInputOtpWebComponent } from "./input-otp-web-component";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
export { Group } from "./parts/Group";
export type { GroupElement } from "./parts/Group";
export { InputOTP } from "./parts/InputOTP";
export type { InputOTPElement } from "./parts/InputOTP";
export { InputOTPGroup } from "./parts/InputOTPGroup";
export type { InputOTPGroupElement } from "./parts/InputOTPGroup";
export { InputOTPSeparator } from "./parts/InputOTPSeparator";
export type { InputOTPSeparatorElement } from "./parts/InputOTPSeparator";
export { InputOTPSlot } from "./parts/InputOTPSlot";
export type { InputOTPSlotElement } from "./parts/InputOTPSlot";
export { Separator } from "./parts/Separator";
export type { SeparatorElement } from "./parts/Separator";
export { Slot } from "./parts/Slot";
export type { SlotElement } from "./parts/Slot";
