export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { defineBadgeElements } from "./define";
export { defineBadgeElements as defineElements } from "./define";
export { createBadgeElement, createElement, getPartSpec } from "./shared";
export type { BadgeHostElement } from "./shared";
export { BadgeElement, BadgeElement as BadgeWebElement } from "./badge-element";
export { createBadgeWebComponent } from "./badge-web-component";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
