export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { definePaginationElements } from "./define";
export { definePaginationElements as defineElements } from "./define";
export { createPaginationElement, createElement, getPartSpec } from "./shared";
export type { PaginationHostElement } from "./shared";
export { PaginationWebElement, createPaginationWebComponent } from "./pagination-element";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
export { Content } from "./parts/Content";
export type { ContentElement } from "./parts/Content";
export { Ellipsis } from "./parts/Ellipsis";
export type { EllipsisElement } from "./parts/Ellipsis";
export { Item } from "./parts/Item";
export type { ItemElement } from "./parts/Item";
export { Link } from "./parts/Link";
export type { LinkElement } from "./parts/Link";
export { Next } from "./parts/Next";
export type { NextElement } from "./parts/Next";
export { Pages } from "./parts/Pages";
export type { PagesElement } from "./parts/Pages";
export { Previous } from "./parts/Previous";
export type { PreviousElement } from "./parts/Previous";
