export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { defineAlertDialogElements } from "./define";
export { defineAlertDialogElements as defineElements } from "./define";
export { createAlertDialogElement, createElement, getPartSpec } from "./shared";
export type { AlertDialogHostElement } from "./shared";
export { AlertDialogWebElement, createAlertDialogWebComponent } from "./alert-dialog-element";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
export { Action } from "./parts/Action";
export type { ActionElement } from "./parts/Action";
export { Cancel } from "./parts/Cancel";
export type { CancelElement } from "./parts/Cancel";
export { Content } from "./parts/Content";
export type { ContentElement } from "./parts/Content";
export { Description } from "./parts/Description";
export type { DescriptionElement } from "./parts/Description";
export { Icon } from "./parts/Icon";
export type { IconElement } from "./parts/Icon";
export { Overlay } from "./parts/Overlay";
export type { OverlayElement } from "./parts/Overlay";
export { Portal } from "./parts/Portal";
export type { PortalElement } from "./parts/Portal";
export { Title } from "./parts/Title";
export type { TitleElement } from "./parts/Title";
export { Trigger } from "./parts/Trigger";
export type { TriggerElement } from "./parts/Trigger";
