export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { defineProgressElements } from "./define";
export { defineProgressElements as defineElements } from "./define";
export { createProgressElement, createElement, getPartSpec } from "./shared";
export type { ProgressHostElement } from "./shared";
export { ProgressElement, ProgressElement as ProgressWebElement } from "./progress-element";
export { createProgressWebComponent } from "./progress-web-component";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
export { Indicator } from "./parts/Indicator";
export type { IndicatorElement } from "./parts/Indicator";
