export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { definePopoverElements } from "./define";
export { definePopoverElements as defineElements } from "./define";
export { createPopoverElement, createElement, getPartSpec } from "./shared";
export type { PopoverHostElement } from "./shared";
export { PopoverWebElement, createPopoverWebComponent } from "./popover-element";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
export { Close } from "./parts/Close";
export type { CloseElement } from "./parts/Close";
export { Content } from "./parts/Content";
export type { ContentElement } from "./parts/Content";
export { Description } from "./parts/Description";
export type { DescriptionElement } from "./parts/Description";
export { Heading } from "./parts/Heading";
export type { HeadingElement } from "./parts/Heading";
export { Trigger } from "./parts/Trigger";
export type { TriggerElement } from "./parts/Trigger";
