export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { defineTableElements } from "./define";
export { defineTableElements as defineElements } from "./define";
export { createTableElement, createElement, getPartSpec } from "./shared";
export type { TableHostElement } from "./shared";
export { TableWebElement, createTableWebComponent } from "./table-element";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
export { Body } from "./parts/Body";
export type { BodyElement } from "./parts/Body";
export { Caption } from "./parts/Caption";
export type { CaptionElement } from "./parts/Caption";
export { Cell } from "./parts/Cell";
export type { CellElement } from "./parts/Cell";
export { ColumnHeader } from "./parts/ColumnHeader";
export type { ColumnHeaderElement } from "./parts/ColumnHeader";
export { Footer } from "./parts/Footer";
export type { FooterElement } from "./parts/Footer";
export { Header } from "./parts/Header";
export type { HeaderElement } from "./parts/Header";
export { Row } from "./parts/Row";
export type { RowElement } from "./parts/Row";
export { RowHeader } from "./parts/RowHeader";
export type { RowHeaderElement } from "./parts/RowHeader";
