export { componentSpec } from "./component-spec";
export type { ComponentPartName, ComponentPartSpec, ComponentSpec } from "./component-spec";
export { defineScrollAreaElements } from "./define";
export { defineScrollAreaElements as defineElements } from "./define";
export { createScrollAreaElement, createElement, getPartSpec } from "./shared";
export type { ScrollAreaHostElement } from "./shared";
export { ScrollAreaWebElement, createScrollAreaWebComponent } from "./scroll-area-element";
export { Root } from "./parts/Root";
export type { RootElement } from "./parts/Root";
export { Corner } from "./parts/Corner";
export type { CornerElement } from "./parts/Corner";
export { Scrollbar } from "./parts/Scrollbar";
export type { ScrollbarElement } from "./parts/Scrollbar";
export { ScrollDownButton } from "./parts/ScrollDownButton";
export type { ScrollDownButtonElement } from "./parts/ScrollDownButton";
export { ScrollUpButton } from "./parts/ScrollUpButton";
export type { ScrollUpButtonElement } from "./parts/ScrollUpButton";
export { Thumb } from "./parts/Thumb";
export type { ThumbElement } from "./parts/Thumb";
export { Viewport } from "./parts/Viewport";
export type { ViewportElement } from "./parts/Viewport";
